export const candidates = [
  {
    id: "1",
    name: "Sarah Chen",
    email: "sarah.chen@gmail.com",
    role: "Senior Frontend Engineer",
    score: 94,
    skills: ["React", "TypeScript", "Next.js", "GraphQL"],
    experience: "7 years",
    status: "shortlisted" as const,
    appliedDate: "2026-02-05",
    summary: "Strong frontend engineer with deep React expertise and experience leading teams at scale. Built component libraries used by 50+ developers.",
    aiExplanation: "Excellent match for the role. 7 years of relevant experience with all required technologies. Previous team lead experience aligns with growth trajectory. Portfolio shows production-quality work.",
  },
  {
    id: "2",
    name: "Marcus Johnson",
    email: "marcus.j@outlook.com",
    role: "Senior Frontend Engineer",
    score: 91,
    skills: ["React", "TypeScript", "Node.js", "AWS"],
    experience: "6 years",
    status: "shortlisted" as const,
    appliedDate: "2026-02-04",
    summary: "Full-stack leaning frontend developer with strong systems thinking. Experience at two YC startups building from 0 to 1.",
    aiExplanation: "Strong candidate with startup experience. Demonstrates ability to work independently and ship quickly. TypeScript proficiency is advanced based on open-source contributions.",
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    email: "emily.r@proton.me",
    role: "Senior Frontend Engineer",
    score: 88,
    skills: ["React", "Vue", "TypeScript", "Figma"],
    experience: "5 years",
    status: "review" as const,
    appliedDate: "2026-02-06",
    summary: "Design-minded frontend engineer who bridges design and engineering. Experience building design systems from scratch.",
    aiExplanation: "Good match overall. Design system experience is a strong plus. Slightly fewer years than ideal but the quality of work compensates. Vue experience may not directly transfer.",
  },
  {
    id: "4",
    name: "David Kim",
    email: "d.kim@yahoo.com",
    role: "Senior Frontend Engineer",
    score: 85,
    skills: ["React", "JavaScript", "CSS", "Testing"],
    experience: "8 years",
    status: "review" as const,
    appliedDate: "2026-02-03",
    summary: "Seasoned frontend developer with deep CSS expertise and accessibility focus. Strong testing background with 90%+ coverage standards.",
    aiExplanation: "Experienced candidate with strong fundamentals. TypeScript listed as learning rather than proficient, which is a gap. Accessibility expertise is valuable but not a primary requirement.",
  },
  {
    id: "5",
    name: "Priya Patel",
    email: "priya.p@gmail.com",
    role: "Senior Frontend Engineer",
    score: 82,
    skills: ["React", "TypeScript", "Python", "ML"],
    experience: "4 years",
    status: "review" as const,
    appliedDate: "2026-02-07",
    summary: "Frontend engineer with ML background. Built interactive data visualization dashboards for healthcare analytics.",
    aiExplanation: "Interesting profile with unique ML crossover. Fewer years of pure frontend than desired. Data visualization skills could be valuable for analytics features.",
  },
  {
    id: "6",
    name: "James Wright",
    email: "j.wright@mail.com",
    role: "Senior Frontend Engineer",
    score: 76,
    skills: ["Angular", "JavaScript", "RxJS"],
    experience: "9 years",
    status: "rejected" as const,
    appliedDate: "2026-02-02",
    summary: "Enterprise Angular developer with strong background in financial services. Expert in complex form handling and state management.",
    aiExplanation: "Experienced developer but primarily Angular-focused. No React or TypeScript experience listed. Would require significant ramp-up time on the tech stack.",
  },
  {
    id: "7",
    name: "Lisa Wang",
    email: "lisa.w@gmail.com",
    role: "Senior Frontend Engineer",
    score: 72,
    skills: ["HTML", "CSS", "jQuery", "WordPress"],
    experience: "10 years",
    status: "rejected" as const,
    appliedDate: "2026-02-01",
    summary: "Web developer with extensive WordPress and traditional web development experience. Strong design sensibility.",
    aiExplanation: "Significant experience but primarily with legacy technologies. No modern framework experience. The role requires React and TypeScript which are not in the candidate's skillset.",
  },
  {
    id: "8",
    name: "Alex Thompson",
    email: "alex.t@company.com",
    role: "Product Designer",
    score: 90,
    skills: ["Figma", "User Research", "Prototyping", "Design Systems"],
    experience: "6 years",
    status: "shortlisted" as const,
    appliedDate: "2026-02-05",
    summary: "Product designer with B2B SaaS experience. Led redesign of a CRM platform that increased user adoption by 40%.",
    aiExplanation: "Strong match for the design role. B2B SaaS experience is directly relevant. Portfolio demonstrates strong systems thinking and user research methodology.",
  },
]

export const roles = [
  {
    id: "1",
    title: "Senior Frontend Engineer",
    department: "Engineering",
    location: "Remote",
    type: "Full-time",
    applicants: 247,
    shortlisted: 8,
    status: "active" as const,
    createdDate: "2026-01-20",
    skills: ["React", "TypeScript", "Next.js"],
    experience: "5+ years",
  },
  {
    id: "2",
    title: "Product Designer",
    department: "Design",
    location: "New York, NY",
    type: "Full-time",
    applicants: 183,
    shortlisted: 5,
    status: "active" as const,
    createdDate: "2026-01-25",
    skills: ["Figma", "User Research", "Prototyping"],
    experience: "4+ years",
  },
  {
    id: "3",
    title: "Backend Engineer",
    department: "Engineering",
    location: "San Francisco, CA",
    type: "Full-time",
    applicants: 312,
    shortlisted: 10,
    status: "active" as const,
    createdDate: "2026-01-15",
    skills: ["Go", "PostgreSQL", "Kubernetes"],
    experience: "5+ years",
  },
  {
    id: "4",
    title: "Data Analyst",
    department: "Analytics",
    location: "Remote",
    type: "Full-time",
    applicants: 156,
    shortlisted: 4,
    status: "closed" as const,
    createdDate: "2026-01-10",
    skills: ["SQL", "Python", "Tableau"],
    experience: "3+ years",
  },
]

export const activityFeed = [
  { id: "1", action: "AI screened 47 resumes", role: "Senior Frontend Engineer", time: "2 minutes ago", type: "screening" as const },
  { id: "2", action: "3 candidates shortlisted", role: "Product Designer", time: "15 minutes ago", type: "shortlist" as const },
  { id: "3", action: "Interview scheduled", role: "Backend Engineer", time: "1 hour ago", type: "scheduling" as const },
  { id: "4", action: "New role created", role: "Data Analyst", time: "3 hours ago", type: "role" as const },
  { id: "5", action: "AI screened 82 resumes", role: "Backend Engineer", time: "5 hours ago", type: "screening" as const },
]

export const schedulingSlots = [
  { id: "1", date: "2026-02-12", time: "09:00 AM", candidate: "Sarah Chen", status: "confirmed" as const },
  { id: "2", date: "2026-02-12", time: "10:30 AM", candidate: "Marcus Johnson", status: "pending" as const },
  { id: "3", date: "2026-02-13", time: "02:00 PM", candidate: "Alex Thompson", status: "confirmed" as const },
  { id: "4", date: "2026-02-14", time: "11:00 AM", candidate: "Emily Rodriguez", status: "pending" as const },
]

export const analyticsData = {
  resumesScreened: [
    { month: "Sep", count: 120 },
    { month: "Oct", count: 245 },
    { month: "Nov", count: 380 },
    { month: "Dec", count: 290 },
    { month: "Jan", count: 420 },
    { month: "Feb", count: 185 },
  ],
  timeSaved: [
    { month: "Sep", hours: 24 },
    { month: "Oct", hours: 48 },
    { month: "Nov", hours: 72 },
    { month: "Dec", hours: 56 },
    { month: "Jan", hours: 84 },
    { month: "Feb", hours: 38 },
  ],
  hiringSpeed: [
    { month: "Sep", days: 28 },
    { month: "Oct", days: 22 },
    { month: "Nov", days: 18 },
    { month: "Dec", days: 15 },
    { month: "Jan", days: 12 },
    { month: "Feb", days: 10 },
  ],
}
